steps:
  - label: ":pip: Prepare conda env and prerequisites"
    key: "conda"
    command: bash .buildkite/install-env.sh

  - label: ":pip: Install lmcache"
    key: "lmcache"
    depends_on: ["conda"]
    command: bash .buildkite/install-lmcache.sh

  - label: ":pip: Install lmcache-vllm"
    key: "vllm"
    depends_on: ["lmcache"]
    command: bash .buildkite/install-vllm.sh

  - label: ":serve: Run server"
    key: "server"
    depends_on: ["vllm"]
    command: bash .buildkite/multi-round-qa-server.sh

  - label: ":test: Run tests"
    key: "test"
    depends_on: ["server"]
    command: bash .buildkite/multi-round-qa.sh
    artifact_paths: summary.csv

  - label: ":clean: Kill all"
    key: "clean"
    depends_on: ["test"]
    command: bash .buildkite/clean.sh
