chunk_size: 1024
local_disk: "file:///home/ubuntu/st-prodstack-v/kvcache/engine1/"
max_local_disk_size: 0
local_cpu: True
max_local_cpu_size: 20 # actually 40 + 5, set to 60 to avoid bubble
alpha: 1
policy: "baseline_KIVI"
rate: 0.371428571
compression: "kivi"
dataset_csv: "/home/ubuntu/shaotingf/cacheserve/oracle_different_method/two_rounds.csv"
method_output_csv: "results/Jun_4_2_sum/baseline_kivi/02_mode.csv"